# Generated by Django 5.1.4 on 2024-12-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='title',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
